# tomcat端口
server:
  port: 80

# github的用户信息
github:
  client:
    id: 60b9e232c55203724978
    secret: eabf577701f1b3e373e7b289aeb32915278887ce
  redirect:
    uri: http://106.75.7.176:80/callback

# spring的数据源
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~\community
    username: root
    password: 123456

# 开启mybatis返回数据类型中划线到驼峰规则的自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.mycz.community.
  mapper-locations: classpath:mapper/*.xml

# 打印mybatis执行的sql
logging:
  level:
    cn.mycz.community.mapper: debug

# ucloud文件上传服务
ucloud:
  ufile:
    public-key: TOKEN_0046698e-bb19-4ee9-ab07-523c2c712adb
    private-key: b9416bb6-dd89-4145-bf91-53688f7112a9
    bucket-name: mycz
    region: cn-bj
    proxy-suffix: ufileos.com
    expires-duration: 315360000
